#
# Index config file for wikipedia dataset.
#

version: 0

index_id: wikipedia

doc_mapping:
  field_mappings:
    - name: title
      type: text
      tokenizer: default
      record: position
      stored: true
    - name: body
      type: text
      tokenizer: default
      record: position
      stored: true
    - name: url
      type: text
      tokenizer: raw

indexing_settings:
  commit_timeout_secs: 3600
  split_num_docs_target: 100000000
  resources:
    heap_size: 4G

search_settings:
  default_search_fields: [title, body]
